apda/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/favicon.ico', permanent=True)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    path("search/", include("haystack.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path

from core.views import (
    admin_views,
    coty_views,
    debater_views,
    noty_views,
    results_import_views,
    round_views,
    school_views,
    soty_views,
    team_views,
    toty_views,
    tournament_views,
    video_views,
    views,
)

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("core/schools/", school_views.SchoolListView.as_view(), name="school_list"),
    path(
        "core/schools/<int:pk>",
        school_views.SchoolDetailView.as_view(),
        name="school_detail",
    ),
    path(
        "core/schools/<int:pk>/edit",
        school_views.SchoolUpdateView.as_view(),
        name="school_update",
    ),
    path(
        "core/schools/<int:pk>/delete",
        school_views.SchoolDeleteView.as_view(),
        name="school_delete",
    ),
    path(
        "core/schools/create",
        school_views.SchoolCreateView.as_view(),
        name="school_create",
    ),
    path(
        "core/schools/autocomplete",
        school_views.SchoolAutocomplete.as_view(),
        name="school_autocomplete",
    ),
    path(
        "core/debaters/", debater_views.DebaterListView.as_view(), name="debater_list"
    ),
    path(
        "core/debaters/<int:pk>",
        debater_views.DebaterDetailView.as_view(),
        name="debater_detail",
    ),
    path(
        "core/debaters/<int:pk>/edit",
        debater_views.DebaterUpdateView.as_view(),
        name="debater_update",
    ),
    path(
        "core/debaters/<int:pk>/delete",
        debater_views.DebaterDeleteView.as_view(),
        name="debater_delete",
    ),
    path(
        "core/debaters/create",
        debater_views.DebaterCreateView.as_view(),
        name="debater_create",
    ),
    path(
        "core/debaters/autocomplete",
        debater_views.DebaterAutocomplete.as_view(),
        name="debater_autocomplete",
    ),
    path("core/teams/", team_views.TeamListView.as_view(), name="team_list"),
    path(
        "core/teams/<int:pk>", team_views.TeamDetailView.as_view(), name="team_detail"
    ),
    path(
        "core/teams/<int:pk>/edit",
        team_views.TeamUpdateView.as_view(),
        name="team_update",
    ),
    path(
        "core/teams/<int:pk>/delete",
        team_views.TeamDeleteView.as_view(),
        name="team_delete",
    ),
    path(
        "core/teams/autocomplete",
        team_views.TeamAutocomplete.as_view(),
        name="team_autocomplete",
    ),
    path("core/videos/", video_views.VideoListView.as_view(), name="video_list"),
    path(
        "core/videos/<int:pk>",
        video_views.VideoDetailView.as_view(),
        name="video_detail",
    ),
    path(
        "core/videos/<int:pk>/edit",
        video_views.VideoUpdateView.as_view(),
        name="video_update",
    ),
    path(
        "core/videos/<int:pk>/delete",
        video_views.VideoDeleteView.as_view(),
        name="video_delete",
    ),
    path(
        "core/videos/create", video_views.VideoCreateView.as_view(), name="video_create"
    ),
    path(
        "core/videos/tags",
        video_views.TagAutocomplete.as_view(create_field="name"),
        name="tag_autocomplete",
    ),
    path(
        "core/videos/tags_no_create",
        video_views.TagAutocomplete.as_view(),
        name="tag_autocomplete_no_create",
    ),
    path(
        "core/videos/tags/<str:slug>",
        video_views.TagDetail.as_view(),
        name="tag_detail",
    ),
    path(
        "core/tournaments/",
        tournament_views.TournamentListView.as_view(),
        name="tournament_list",
    ),
    path(
        "core/schedules/", tournament_views.ScheduleView.as_view(), name="schedule_view"
    ),
    path(
        "core/tournaments/<int:pk>",
        tournament_views.TournamentDetailView.as_view(),
        name="tournament_detail",
    ),
    path(
        "core/tournaments/<int:pk>/edit",
        tournament_views.TournamentUpdateView.as_view(),
        name="tournament_update",
    ),
    path(
        "core/tournaments/<int:pk>/delete",
        tournament_views.TournamentDeleteView.as_view(),
        name="tournament_delete",
    ),
    path(
        "core/tournaments/create",
        tournament_views.TournamentCreateView.as_view(),
        name="tournament_create",
    ),
    path(
        "core/tournaments/autocomplete",
        tournament_views.TournamentAutocomplete.as_view(),
        name="tournament_autocomplete",
    ),
    path(
        "core/tournaments/all_autocomplete",
        tournament_views.AllTournamentAutocomplete.as_view(),
        name="all_tournament_autocomplete",
    ),
    path(
        "core/tournaments/data_entry",
        results_import_views.TournamentDataEntryWizardView.as_view(),
        name="tournament_dataentry",
    ),
    path(
        "core/tournaments/get_new_form",
        results_import_views.get_new_team_form,
        name="get_new_team_form",
    ),
    path(
        "core/rounds/<int:pk>",
        round_views.RoundDetailView.as_view(),
        name="round_detail",
    ),
    path("core/soty", soty_views.SOTYListView.as_view(), name="soty"),
    path("core/toty", toty_views.TOTYListView.as_view(), name="toty"),
    path("core/noty", noty_views.NOTYListView.as_view(), name="noty"),
    path("core/coty", coty_views.COTYListView.as_view(), name="coty"),
    path("core/admin-tools/", admin_views.AdminToolsView.as_view(), name="admin_tools"),
    path(
        "core/mittab-dashboard/",
        admin_views.MitTabDashboardView.as_view(),
        name="mittab_dashboard",
    ),
    path(
        "core/rankings-recompute/",
        admin_views.RankingsRecomputeView.as_view(),
        name="rankings_recompute",
    ),
]

core/models/debater.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

from .school import School


class Debater(models.Model):
    first_name = models.CharField(max_length=32, blank=False)

    last_name = models.CharField(max_length=32, blank=False)

    school = models.ForeignKey(
        School,
        on_delete=models.SET_NULL,
        related_name="debaters",
        blank=True,
        null=True,
    )
    # WHAT IF AFFILIATION CHANGES ?  Considered new debater

    first_season = models.CharField(max_length=16, blank=True, null=True)
    latest_season = models.CharField(max_length=16, blank=True, null=True)

    NOVICE = 0
    VARSITY = 1
    STATUS = ((VARSITY, "Varsity"), (NOVICE, "Novice"))
    status = models.IntegerField(choices=STATUS, default=VARSITY)

    def save(self, *args, **kwargs):
        if not self.pk:
            current_season = settings.CURRENT_SEASON
            if not self.first_season:
                self.first_season = current_season
            if not self.latest_season:
                self.latest_season = current_season
        super().save(*args, **kwargs)

        for team in self.teams.all():
            team.update_name()
            team.save()

    @property
    def name(self):
        name = f"{self.first_name} {self.last_name}"
        return name.strip()

    def get_absolute_url(self):
        return reverse("core:debater_detail", kwargs={"pk": self.id})

    def __str__(self):
        return self.name


class QualPoints(models.Model):
    # THIS IS FUNCTIONALLY QUAL POINTS (EXCLUDED 6 FOR QUALLING ITSELF)

    debater = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="qual_points"
    )

    points = models.FloatField(default=0)

    season = models.CharField(max_length=16)

    @property
    def qualled(self):
        return self.debater.quals.filter(season=self.season).exists()

    def __save__(self, *args, **kwargs):
        if not self.season:
            self.season = settings.CURRENT_SEASON
        super().save(*args, **kwargs)


class Reaff(models.Model):
    season = models.CharField(max_length=16)

    old_debater = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="reaff_old"
    )

    new_debater = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="reaff_new"
    )
    reaff_date = models.DateField()

    def __save__(self, *args, **kwargs):
        if not self.season:
            self.season = settings.CURRENT_SEASON
        super().save(*args, **kwargs)

core/models/round.py
from django.db import models
from django.shortcuts import reverse

from .debater import Debater
from .team import Team
from .tournament import Tournament


class Round(models.Model):
    gov = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="govs")

    opp = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="opps")

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="rounds"
    )

    round_number = models.IntegerField(default=0)

    UNKNOWN = 0
    GOV = 1
    OPP = 2
    GOV_VIA_FORFEIT = 3
    OPP_VIA_FORFEIT = 4
    ALL_DROP = 5
    ALL_WIN = 6
    VICTOR_CHOICES = (
        (UNKNOWN, "UNKNOWN"),
        (GOV, "GOV"),
        (OPP, "OPP"),
        (GOV_VIA_FORFEIT, "GOV via Forfeit"),
        (OPP_VIA_FORFEIT, "OPP via Forfeit"),
        (ALL_DROP, "ALL DROP"),
        (ALL_WIN, "ALL WIN"),
    )

    victor = models.IntegerField(choices=VICTOR_CHOICES, default=0)

    # JUDGES TO DO

    def get_absolute_url(self):
        return reverse("core:round_detail", kwargs={"pk": self.id})


class RoundStats(models.Model):
    debater = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="round_stats"
    )

    round = models.ForeignKey(Round, on_delete=models.CASCADE, related_name="stats")

    speaks = models.DecimalField(max_digits=6, decimal_places=4)
    ranks = models.DecimalField(max_digits=6, decimal_places=4)
    debater_role = models.CharField(max_length=4, null=True)

core/models/school.py
from django.db import models
from django.shortcuts import reverse


class School(models.Model):
    name = models.CharField(max_length=64, blank=False, unique=True)

    included_in_oty = models.BooleanField(default=True, verbose_name="Included in OTY")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:school_detail", kwargs={"pk": self.id})


class SchoolLookup(models.Model):
    server_name = models.CharField(max_length=64, blank=False, unique=True)

    school = models.ForeignKey(
        School, on_delete=models.CASCADE, related_name="school_lookups"
    )

core/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    can_view_private_videos = models.BooleanField(default=False)

core/models/video.py
from django.db import models
from django.shortcuts import reverse
from taggit.managers import TaggableManager

from core.models.debater import Debater
from core.models.tournament import Tournament


class Video(models.Model):
    pm = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="pm_videos", verbose_name="PM"
    )

    lo = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="lo_videos", verbose_name="LO"
    )

    mg = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="mg_videos", verbose_name="MG"
    )

    mo = models.ForeignKey(
        Debater, on_delete=models.CASCADE, related_name="mo_videos", verbose_name="MO"
    )

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="videos"
    )

    UNKNOWN = 0
    ROUND_ONE = 1
    ROUND_TWO = 2
    ROUND_THREE = 3
    ROUND_FOUR = 4
    ROUND_FIVE = 5
    ROUND_SIX = 14
    VO = 6
    VQ = 7
    VS = 8
    VF = 9
    NQ = 10
    NS = 11
    NF = 12
    DEMO = 13
    ROUNDS = (
        (UNKNOWN, "UNKNOWN"),
        (ROUND_ONE, "1"),
        (ROUND_TWO, "2"),
        (ROUND_THREE, "3"),
        (ROUND_FOUR, "4"),
        (ROUND_FIVE, "5"),
        (ROUND_SIX, "6"),
        (VO, "Varsity Octafinals"),
        (VQ, "Varsity Quarterfinals"),
        (VS, "Varsity Semifinals"),
        (VF, "Varsity Finals"),
        (NQ, "Novice Quarterfinals"),
        (NS, "Novice Semifinals"),
        (NF, "Novice Finals"),
        (DEMO, "Demo Round"),
    )

    round = models.IntegerField(choices=ROUNDS, default=UNKNOWN)

    case = models.TextField(blank=True)
    description = models.TextField(blank=True)

    link = models.CharField(max_length=4096)
    password = models.CharField(max_length=1024, blank=True, help_text="If needed")

    ALL = 0
    ACCOUNTS_ONLY = 1
    DEBATERS_IN_ROUND = 2
    PERMISSIONS = (
        (ALL, "All"),
        (ACCOUNTS_ONLY, "Accounts Only"),
        (DEBATERS_IN_ROUND, "Debaters in Round"),
    )
    permissions = models.IntegerField(choices=PERMISSIONS, default=DEBATERS_IN_ROUND)

    tags = TaggableManager(blank=True)

    def get_absolute_url(self):
        return reverse("core:video_detail", kwargs={"pk": self.id})

    def __str__(self):
        return f"{self.tournament.name} / {self.tournament.get_season_display()} / {self.get_round_display()}"

core/views.py
from django.shortcuts import render

from django.conf import settings

from core.models import (
    TOTY,
    SOTY,
    NOTY,
    COTY
)

# Create your views here.


def index(request):
    toty = TOTY.objects.filter(season=settings.CURRENT_SEASON).order_by('-points').all()
    coty = COTY.objects.filter(season=settings.CURRENT_SEASON).order_by('-points').all()
    soty = SOTY.objects.filter(season=settings.CURRENT_SEASON).order_by('-points').all()
    noty = NOTY.objects.filter(season=settings.CURRENT_SEASON).order_by('-points').all()

    return render(request,
                  'core/index.html',
                  locals())

core/views/coty_views.py
from django.conf import settings
from django.shortcuts import redirect, reverse
from django_filters import FilterSet
from django_tables2 import Column

from core.models.standings.coty import COTY
from core.utils.generics import (
    CustomListView,
    CustomTable,
    PlaceColumn,
    PointsColumn,
)


class COTYFilter(FilterSet):
    class Meta:
        model = COTY
        fields = {
            "school__id": ["exact"],
            "school__name": ["icontains"],
            "season": ["exact"],
        }


class COTYTable(CustomTable):
    school = Column(
        verbose_name="School",
        accessor="school__name",
        linkify=lambda record: record.school.get_absolute_url(),
    )

    place = PlaceColumn()

    points = PointsColumn()

    class Meta:
        model = COTY
        fields = ("place", "school", "points")


class COTYListView(CustomListView):
    public_view = True
    model = COTY
    table_class = COTYTable
    template_name = "cotys/list.html"

    filterset_class = COTYFilter

    def get(self, request, *args, **kwargs):
        if not self.request.GET.get("season"):
            return redirect(reverse("core:coty") + "?season=" + settings.CURRENT_SEASON)
        return super().get(request, *args, **kwargs)

core/views/noty_views.py
from django.conf import settings
from django.shortcuts import redirect, reverse
from django_filters import FilterSet
from django_tables2 import Column

from core.models.standings.noty import NOTY
from core.utils.generics import (
    CustomListView,
    CustomTable,
    MarkerColumn,
    PlaceColumn,
    PointsColumn,
)


class NOTYFilter(FilterSet):
    class Meta:
        model = NOTY
        fields = {
            "debater__id": ["exact"],
            "debater__first_name": ["icontains"],
            "debater__last_name": ["icontains"],
            "debater__school__name": ["icontains"],
            "season": ["exact"],
        }


class NOTYTable(CustomTable):
    place = PlaceColumn()

    points = PointsColumn()

    marker_one = MarkerColumn(number="one", verbose_name="1")
    marker_two = MarkerColumn(number="two", verbose_name="2")
    marker_three = MarkerColumn(number="three", verbose_name="3")
    marker_four = MarkerColumn(number="four", verbose_name="4")
    marker_five = MarkerColumn(number="five", verbose_name="5")

    debater = Column(
        verbose_name="Debater",
        accessor="debater__name",
        linkify=lambda record: record.debater.get_absolute_url(),
    )
    school = Column(
        verbose_name="School",
        accessor="debater__school__name",
        linkify=lambda record: record.debater.school.get_absolute_url(),
    )

    class Meta:
        model = NOTY
        fields = (
            "place",
            "debater",
            "school",
            "points",
            "marker_one",
            "marker_two",
            "marker_three",
            "marker_four",
            "marker_five",
        )


class NOTYListView(CustomListView):
    public_view = True
    model = NOTY
    table_class = NOTYTable
    template_name = "notys/list.html"

    filterset_class = NOTYFilter

    def get(self, request, *args, **kwargs):
        if not self.request.GET.get("season"):
            return redirect(reverse("core:noty") + "?season=" + settings.CURRENT_SEASON)
        return super().get(request, *args, **kwargs)

core/views/round_views.py
from core.models.round import Round
from core.utils.generics import (
    CustomDetailView,
)


class RoundDetailView(CustomDetailView):
    public_view = True
    model = Round
    template_name = "rounds/detail.html"

core/templates/videos/create.html
{% extends "base/create.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row mt-5 mb-5 mr-2 ml-2">
        <div class="col-lg-8">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title pb-2">Create Video</h5>
                    {% crispy form %}
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card sticky-top mb-2" style="top: 30px;">
                <div class="card-body">
                    <h5 class="card-title">Create Debater</h5>
                    <a href="{% url 'core:school_create' %}" target="_blank">Create new school</a>
                    <hr />
                    <form id="debater_create_form">
                        {% csrf_token %}
                        <input type="hidden" name="ajax" value="1">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="textinput textInput form-control" id="id_name">
                        </div>
                        {{ debater_form.school|as_crispy_field }}
                        <input class="btn btn-primary"
                               id="create_debater"
                               value="Create"
                               type="submit">
                    </form>
                </div>
            </div>
            <div class="card sticky-top" style="top: 369px" px;">
                <div class="card-body">
                    <h5 class="card-title">Created Debaters</h5>
                    <ul id="new_debaters">
                    </ul>
                </div>
            </div>
        </div>
{% endblock content %}

core/templates/videos/delete.html
{% extends "base/delete.html" %}

core/templates/videos/detail.html
{% extends "base/detail.html" %}
{% load tags %}
{% block title %}
    {{ object }}
{% endblock title %}
{% block detail_view %}
    <table class="table table-bordered">
        <thead>
            <th>Field</th>
            <th>Value</th>
        </thead>
        <tbody>
            <tr>
                <td>Tournament</td>
                <td>
                    <a href="{{ object.tournament.get_absolute_url }}">{{ object.tournament.name }}</a> ({{ object.tournament.get_season_display }})
                </td>
            </tr>
            <tr>
                <td>Round</td>
                <td>{{ object.get_round_display }}</td>
            </tr>
        <tr>
            <td>PM</td>
            <td>
                <a href="{{ object.pm.get_absolute_url }}">{{ object.pm.name }}</a>
            </td>
        </tr>
        <tr>
            <td>MG</td>
            <td>
                <a href="{{ object.mg.get_absolute_url }}">{{ object.mg.name }}</a>
            </td>
        </tr>
        <tr>
            <td>LO</td>
            <td>
                <a href="{{ object.lo.get_absolute_url }}">{{ object.lo.name }}</a>
            </td>
        </tr>
        <tr>
            <td>MO</td>
            <td>
                <a href="{{ object.mo.get_absolute_url }}">{{ object.mo.name }}</a>
            </td>
        </tr>
        <tr>
            <td>Link</td>
            <td>
                <a href="{{ object.link }}">Link</a>
            </td>
        </tr>
        <tr>
            <td>Password</td>
            <td>
                {% if object.password != '' %}
                    {{ object.password }}
                {% else %}
                    No Password
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Permissions</td>
            <td>{{ object.get_permissions_display }}</td>
        </tr>
    </tbody>
</table>
{% endblock detail_view %}
{% block added_information_view %}
    <div class="card">
        <div class="card-body">
            {% if embed %}
                <div class="row">
                    <div class="col-lg-8">
                        <iframe width="100%"
                            height=480"
                            src="{{ embed_link }}"
                            allow="autoplay; fullscreen"
                            allowfullscreen>
                        </iframe>
                    </div>
                    <div class="col-lg-4">
                        <h6>Case:</h6>
                        {% if object.case != '' %}
                            {{ object.case|safe }}
                        {% else %}
                            There is no data in this field
                        {% endif %}
                    </div>
                </div>
                <hr />
            {% else %}
                <h5 class="card-title pb-2">Video Descriptors</h5>
                <h6>Case:</h6>
                {% if object.case != '' %}
                    {{ object.case|safe }}
                {% else %}
                    There is no data in this field
                {% endif %}
                <hr />
            {% endif %}
            <h6>Description:</h6>
            {% if object.description != '' %}
                {{ object.description|safe }}
            {% else %}
                There is no data in this field
            {% endif %}
            <hr />
            <h6>Tags</h6>
            {% for tag in object.tags.all %}
                <a href="{% url 'core:tag_detail' tag.name %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock added_information_view %}

core/templates/videos/list.html
{% extends "base/list.html" %}
{% block table_title %}
    Videos
{% endblock table_title %}

core/templates/videos/update.html
{% extends "videos/detail.html" %}
{% load crispy_forms_tags %}
{% block added_information_view %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit {{ object }}</h5>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.media }}
                {{ form|crispy }}
                <input type="submit" class="btn btn-secondary" value="Save">
            </form>
        </div>
    </div>
{% endblock added_information_view %}